package com.example.valentina.talkwithme;

import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;
import android.view.View;
import android.widget.AdapterView;
import android.widget.GridView;

import com.example.valentina.talkwithme.utilities.MySubject;

import org.json.JSONArray;
import org.json.JSONObject;

public class SubjectSelection extends AppCompatActivity {
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.subject_selection);

        //extraction of all the subject_ids associated to the
        SharedPreferences pref;
        pref = getApplicationContext().getSharedPreferences("userData", Context.MODE_PRIVATE);
        String subject_id_name = pref.getString("DBrelated_subject_id_name", "none");
        //evaluate if there are subjects
        JSONArray subject_id = new JSONArray();
        JSONArray subject_name = new JSONArray();

        if (!"none".equals(subject_id_name)) {
            try {
                JSONArray jsonsubject_id_name = new JSONArray(subject_id_name);
                String numberOfSubject = String.valueOf(jsonsubject_id_name.length());

                SharedPreferences.Editor editor;
                SharedPreferences pref3;
                pref3 = getApplicationContext().getSharedPreferences("TemporalFile", Context.MODE_PRIVATE);
                editor = pref3.edit();
                editor.putString("selected_subject_number", numberOfSubject);

                for (int i = 0; i < jsonsubject_id_name.length(); ++i) {
                    JSONObject ijsonobject = jsonsubject_id_name.getJSONObject(i);
                    String ijsonobject_name = ijsonobject.getString("subject_name");
                    String ijsonobject_id = ijsonobject.getString("subject_id");

                    subject_name.put(ijsonobject_name);
                    subject_id.put(ijsonobject_id);
                }
            } catch (Throwable t) {
                Log.e("My App", "Could not parse malformed JSON: \"" + subject_id_name + "\"");
            }
        }

        GridView mgridview = findViewById(R.id.GridViewSubjectSelection);
        final MySubject[] subjects_autogenerated = createSubjects(subject_name, subject_id);
        final SubjectAdapter subjectsAdapter = new SubjectAdapter(this, subjects_autogenerated);
        mgridview.setAdapter(subjectsAdapter);

        //set click event on grid elements
        mgridview.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                MySubject subject = subjects_autogenerated[position];
                subjectsAdapter.notifyDataSetChanged();

                //save selected subject
                //file name: TemporalFile
                SharedPreferences.Editor editor;
                SharedPreferences pref;
                pref = getApplicationContext().getSharedPreferences("TemporalFile", Context.MODE_PRIVATE);
                editor = pref.edit();
                editor.putString("selected_subject_name", subject.getName());
                editor.putString("selected_subject_id", subject.getId());
                editor.putInt("selected_subject_image",subject.getImageResource());
                editor.apply();

                Intent OpenMenu = new Intent(SubjectSelection.this, MultipleSubjectsMenu.class);
                startActivity(OpenMenu);
            }
        });

    }

    /*************************************************************************************/

    private MySubject[] createSubjects(JSONArray subject_name, JSONArray subject_id) {
        MySubject[] subject_fromFor = new MySubject[subject_name.length()];
        for (int i = 0; i < subject_name.length(); ++i) {
            try {
                String subjectName = subject_name.getString(i);
                String subjectID = subject_id.getString(i);
                int ImageResource = R.mipmap.child1_round;
                subject_fromFor[i] = new MySubject(subjectName, subjectID, ImageResource);
            } catch (Throwable t) {
                Log.e("My App", "Could not parse malformed JSON: \"" + subject_name + "\"");
            }
        }
        return subject_fromFor;
    }
}
